/*
 * File: app/store/Tasks.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.store.Tasks', {
    extend: 'Ext.data.Store',

    requires: [
        'TaskManager.model.Task',
        'Ext.util.Sorter'
    ],

    config: {
        model: 'TaskManager.model.Task',
        storeId: 'Tasks',
        sorters: {
            sorterFn: function(first, second) {
                // Completed goes last
                if (first.get('completed') && !second.get('completed')) {
                    return 1;
                } else if (!first.get('completed') && second.get('completed')) {
                    return -1;
                }

                // And then date
                if (first.get('dueDate') && !second.get('dueDate')) {
                    return -1;
                } else if (!first.get('dueDate') && second.get('dueDate')) {
                    return 1;
                }
                return (first.get('dueDate') > second.get('dueDate') ? 1 : -1);
            }
        }
    }
});