/*
 * File: app/model/Task.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.model.Task', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasOne',
        'Ext.data.proxy.Rest'
    ],
    uses: [
        'TaskManager.model.User'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                allowNull: false,
                name: 'description',
                type: 'string'
            },
            {
                allowNull: false,
                name: 'priority',
                type: 'string'
            },
            {
                dateFormat: 'c',
                name: 'dueDate',
                type: 'date'
            },
            {
                allowNull: false,
                defaultValue: false,
                name: 'completed',
                type: 'boolean'
            },
            {
                allowNull: false,
                name: 'userId',
                type: 'auto'
            }
        ],
        hasOne: {
            primaryKey: 'userId',
            model: 'TaskManager.model.User',
            foreignKey: 'id'
        },
        proxy: {
            type: 'rest',
            url: 'task'
        }
    },

    constructor: function() {
        this.callParent(arguments);
        this.getProxy().setUrl(TaskManager.restUrl + 'task');
    }

});