/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.model.User', {
    extend: 'Ext.data.Model',
    alias: 'model.user',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Rest'
    ],

    config: {
        fields: [
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'password',
                type: 'string'
            },
            {
                name: 'username',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'presence',
                field: 'email'
            },
            {
                type: 'email',
                field: 'email'
            },
            {
                type: 'presence',
                field: 'name'
            },
            {
                type: 'presence',
                field: 'password'
            },
            {
                type: 'presence',
                field: 'username'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'user'
        }
    },

    constructor: function() {
        this.callParent(arguments);
        this.getProxy().setUrl(TaskManager.restUrl + 'user');
    }

});