/*
 * File: app/view/RegisterPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.RegisterPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerform',

    requires: [
        'TaskManager.view.MessageLabel',
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Label',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                locales: {
                    instructions: 'panels.fieldset_istruction'
                },
                items: [
                    {
                        xtype: 'textfield',
                        locales: {
                            label: 'panels.register.name'
                        },
                        label: 'Name',
                        labelWidth: '40%',
                        name: 'name',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        locales: {
                            label: 'panels.register.username'
                        },
                        label: 'Username',
                        labelWidth: '40%',
                        name: 'username',
                        required: true
                    },
                    {
                        xtype: 'emailfield',
                        locales: {
                            label: 'panels.register.email'
                        },
                        label: 'Email',
                        labelWidth: '40%',
                        name: 'email',
                        required: true,
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        locales: {
                            label: 'panels.register.password'
                        },
                        label: 'Password',
                        labelWidth: '40%',
                        name: 'password'
                    }
                ]
            },
            {
                xtype: 'messagelabel',
                locales: {
                    html: 'panels.register.error_label'
                },
                hidden: true
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        locales: {
                            text: 'panels.register.b_register'
                        },
                        flex: 1,
                        itemId: 'doRegistrationButton',
                        maxWidth: 150,
                        ui: 'confirm',
                        iconCls: 'compose',
                        text: 'Register'
                    }
                ]
            }
        ]
    }

});