/*
 * File: app/view/TaskList.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskManager.view.TaskList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.tasklist',

    requires: [
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        store: 'Tasks',
        itemTpl: Ext.create('Ext.XTemplate', 
            '<div>',
            '    <tpl if="completed"><img src="resources/images/check.png">',
            '        <span style="text-decoration: line-through;">',
            '            {[this.getPriority(values.priority)]} - {description}',
            '            <tpl if="dueDate"> - {dueDate:date("d-M-Y")}</tpl>',
            '        </span>',
            '    <tpl else>    ',
            '        {[this.getPriority(values.priority)]} - {description}',
            '        <tpl if="dueDate"> - {dueDate:date("d-M-Y")}</tpl>',
            '        </tpl>',
            '</div>',
            {
                getPriority: function(p) {
                    var retval = '';
                    switch(p){
                        case '1': retval = '<span style="color:green;font-weight:bold">' + Ux.locale.Manager.get("panels.task.priorities.low") + '</span>'; break;
                        case '2': retval = '<span style="color:#DCDC00;font-weight:bold">' + Ux.locale.Manager.get("panels.task.priorities.normal") + '</span>'; break;
                        case '3': retval = '<span style="color:red;font-weight:bold">' + Ux.locale.Manager.get("panels.task.priorities.high") + '</span>'; break;
                    }
                    return retval;
                }
            }
        ),
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        locales: {
                            text: 'buttons.new'
                        },
                        flex: 1,
                        itemId: 'addButton',
                        maxWidth: 150,
                        iconCls: 'add',
                        text: 'New'
                    }
                ]
            }
        ]
    }

});